### ISSUE TITLE
Listen for newly installed extensions and monitor them automatically

### ISSUE THREAD

**Issue by rpl** [mozilla/extension-activity-monitor#23]
When the extension activity monitor is monitoring all the extensions and it is active, it should monitor for newly installed extensions and automatically monitor them.

**Comment by Rob--W** [comment]
The management API can be used to observe these events: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management#Events

**Comment by himanshujaidka** [comment]
Should I work on this?

**Comment by Rob--W** [comment]
Hi @himanshujaidka, thanks for your interest. This task is part of a GSoC project, and @atiqueahmedziad is supposed to do this.

I am willing to mentor you on another Mozilla project if you're interested. I saw that you've forked FirefoxColor, would you be interested in contributing over there? Since this topic is not relevant for this issue/project, send me an e-mail to continue the conversation.

**Comment by himanshujaidka** [comment]
yeah sure @Rob--W

**Comment by himanshujaidka** [comment]
Thanks for your reply. I need a mentor who guides me and I am ready to do
hard work. Please guide me and tell me how I'll make a contribution :(

**Comment by himanshujaidka** [comment]
It's my humble request if you will help me. I am a single parent-child from
India and ready to do hard work and want to make my carrier but
unfortunately, due to lack of guidance, I am not able to concentrate on
specific things. I want to crack GSoC 2021 so I choose Mozilla
organization. I have various skills but looking for a mentor. I will be
lucky if you are mentoring me in cracking GSoC 2021 for Mozilla. Hoping
that you will reply me :)

**Comment by himanshujaidka** [comment]
@Rob--W please see your mail
