### ISSUE TITLE
Why you are not using jquery?

### ISSUE THREAD

**Issue by himanshujaidka** [mozilla/extension-activity-monitor#37]
The use of the latest tool will reduce code and it will look more attractive. If you don't mind I will replace all js code with jquery

**Comment by cadeyrn** [comment]
There is really no reason to use a large library like jQuery if you a) are able to write JavaScript b) don't need to care about cross browser compatibility and c) live in the year 2020. It only adds a dependency that you have to maintain (security), makes reviews more time consuming  and can have a performance impact due to the large size of the library. So if the project already works without jQuery what's the point of rewriting the script? "it will look more attractive" it's not a reason at all.

**Comment by himanshujaidka** [comment]
ok ok !
